# THIS DOCKERFILE IS INTENDED FOR DEVELOPMENT ENVIRONMENTS
# DO NOT USE THIS FOR PRODUCTION USAGES.

version: "3"
services:
  database:
    container_name: database
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '{{TYPEORM_DATABASE}}'
      MYSQL_USER: '{{TYPEORM_PASSWORD}}'
      MYSQL_PASSWORD: '{{TYPEORM_USERNAME}}'
    ports:
      - "{{TYPEORM_PORT}}:3306"
