# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        TYPEORM_CONNECTION: mysql
        TYPEORM_HOST: localhost
        TYPEORM_PORT: 3306
        TYPEORM_USERNAME: test
        TYPEORM_PASSWORD: test
        TYPEORM_DATABASE: test
        TYPEORM_SYNCHRONIZE: false
        TYPEORM_LOGGING: error
        TYPEORM_ENTITIES: src/**/*.entity.ts
        TYPEORM_MIGRATIONS: src/migrations/*.ts
        TYPEORM_MIGRATIONS_DIR: src/database/migrations
        TYPEORM_DRIVER_EXTRA: '{"charset": "utf8mb4"}'
        JWT_SECRET: loremIpsumDolor

    - run: yarn install
    - run: yarn lint
    - run: yarn test
